=== EndymionSpr/SEWD_4/XML-Schema.zip_expanded/XML-Schema/TworzenieWlasnychSchematow/emp1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" attributeFormDefault="unqualified">
<xs:element name="PRACOWNICY">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="PRACOWNIK" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ID_PRAC" type="xs:integer"/>
              <xs:element name="NAZWISKO" type="xs:string"/>
              <xs:element name="ETAT" type="xs:string"/>
              <xs:element name="ID_SZEFA" type="xs:integer" minOccurs="0"/>
              <xs:element name="ZATRUDNIONY" type="xs:date"/>
              <xs:element name="PLACA_POD" type="xs:decimal"/>
              <xs:element name="PLACA_DOD" type="xs:decimal" minOccurs="0"/>
              <xs:element name="ID_ZESP" type="xs:integer"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== EndymionSpr/SEWD_4/XML-Schema.zip_expanded/XML-Schema/TworzenieWlasnychSchematow/emp1.xml
<?xml version="1.0"?>
<PRACOWNICY xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="emp1.xsd">
 <PRACOWNIK>
  <ID_PRAC>100</ID_PRAC>
  <NAZWISKO>WEGLARZ</NAZWISKO>
  <ETAT>DYREKTOR</ETAT>
  <ZATRUDNIONY>1968-01-01</ZATRUDNIONY>
  <PLACA_POD>1730</PLACA_POD>
  <PLACA_DOD>420.5</PLACA_DOD>
  <ID_ZESP>10</ID_ZESP>
 </PRACOWNIK>
 <PRACOWNIK>
  <ID_PRAC>110</ID_PRAC>
  <NAZWISKO>BLAZEWICZ</NAZWISKO>
  <ETAT>PROFESOR</ETAT>
  <ID_SZEFA>100</ID_SZEFA>
  <ZATRUDNIONY>1973-05-01</ZATRUDNIONY>
  <PLACA_POD>1350</PLACA_POD>
  <PLACA_DOD>210</PLACA_DOD>
  <ID_ZESP>40</ID_ZESP>
 </PRACOWNIK>
 <PRACOWNIK>
  <ID_PRAC>120</ID_PRAC>
  <NAZWISKO>SLOWINSKI</NAZWISKO>
  <ETAT>PROFESOR</ETAT>
  <ID_SZEFA>100</ID_SZEFA>
  <ZATRUDNIONY>1977-09-01</ZATRUDNIONY>
  <PLACA_POD>1177</PLACA_POD>
  <ID_ZESP>30</ID_ZESP>
 </PRACOWNIK>
 <PRACOWNIK>
  <ID_PRAC>130</ID_PRAC>
  <NAZWISKO>BRZEZINSKI</NAZWISKO>
  <ETAT>PROFESOR</ETAT>
  <ID_SZEFA>100</ID_SZEFA>
  <ZATRUDNIONY>1968-07-01</ZATRUDNIONY>
  <PLACA_POD>960</PLACA_POD>
  <ID_ZESP>20</ID_ZESP>
 </PRACOWNIK>
</PRACOWNICY>
