=== EndymionSpr/SEWD_4/XML-Schema.zip_expanded/XML-Schema/IntegracjaSchematow/prac.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="qualified" attributeFormDefault="unqualified"
  targetNamespace="www.pp.pl/prac">
  <xs:element name="PRACOWNICY">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ROW" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="ID_PRAC" type="xs:string"/>
              <xs:element name="NAZWISKO" type="xs:string"/>
              <xs:element name="ETAT" type="xs:string"/>
              <xs:element name="ID_SZEFA" type="xs:string"
                minOccurs="0"/>
              <xs:element name="ZATRUDNIONY" type="xs:string"/>
              <xs:element name="PLACA_POD" type="xs:string"/>
              <xs:element name="PLACA_DOD" type="xs:string"
                minOccurs="0"/>
              <xs:element name="ID_ZESP" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== EndymionSpr/SEWD_4/XML-Schema.zip_expanded/XML-Schema/IntegracjaSchematow/prac.xml
<?xml version="1.0" encoding="UTF-8"?>
<PRACOWNICY xmlns="www.pp.pl/prac" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="www.pp.pl/prac prac.xsd">
	<ROW>
		<ID_PRAC>100</ID_PRAC>
		<NAZWISKO>WEGLA RZ</NAZWISKO>
		<ETAT>DYREKTOR</ETAT>
		<ZATRUDNIONY>68/01/01</ZATRUDNIONY>
		<PLACA_POD>1730</PLACA_POD>
		<PLACA_DOD>420,5</PLACA_DOD>
		<ID_ZESP>10</ID_ZESP>
	</ROW>
	<ROW>
		<ID_PRAC>110</ID_PRAC>
		<NAZWISKO>BLAZEWICZ</NAZWISKO>
		<ETAT>PROFESOR</ETAT>
		<ID_SZEFA>100</ID_SZEFA>
		<ZATRUDNIONY>73/05/01</ZATRUDNIONY>
		<PLACA_POD>1350</PLACA_POD>
		<PLACA_DOD>210</PLACA_DOD>
		<ID_ZESP>40</ID_ZESP>
	</ROW>
	<ROW>
		<ID_PRAC>120</ID_PRAC>
		<NAZWISKO>SLOWINSKI</NAZWISKO>
		<ETAT>PROFESOR</ETAT>
		<ID_SZEFA>100</ID_SZEFA>
		<ZATRUDNIONY>77/09/01</ZATRUDNIONY>
		<PLACA_POD>1070</PLACA_POD>
		<ID_ZESP>30</ID_ZESP>
	</ROW>
	<ROW>
		<ID_PRAC>130</ID_PRAC>
		<NAZWISKO>BRZEZINSKI</NAZWISKO>
		<ETAT>PROFESOR</ETAT>
		<ID_SZEFA>100</ID_SZEFA>
		<ZATRUDNIONY>68/07/01</ZATRUDNIONY>
		<PLACA_POD>96 0</PLACA_POD>
		<ID_ZESP>20</ID_ZESP>
	</ROW>
	<ROW>
		<ID_PRAC>140</ID_PRAC>
		<NAZWISKO>MORZY</NAZWISKO>
		<ETAT>PROFESOR</ETAT>
		<ID_SZEFA>130</ID_SZEFA>
		<ZATRUDNIONY>75/09/15</ZATRUDNIONY>
		<PLACA_POD>830</PLACA_POD>
		<PLACA_DOD>10 5</PLACA_DOD>
		<ID_ZESP>20</ID_ZESP>
	</ROW>
	<ROW>
		<ID_PRAC>150</ID_PRAC>
		<NAZWISKO>KROLIKOWSKI</NAZWISKO>
		<ETAT>ADIUNKT</ETAT>
		<ID_SZEFA>130</ID_SZEFA>
		<ZATRUDNIONY>77/09/01</ZATRUDNIONY>
		<PLACA_POD>645,5</PLACA_POD>
		<ID_ZESP>20</ID_ZESP>
	</ROW>
	<ROW>
		<ID_PRAC>160</ID_PRAC>
		<NAZWISKO>KOSZLAJDA</NAZWISKO>
		<ETAT>ADIUNKT</ETAT>
		<ID_SZEFA>130</ID_SZEFA>
		<ZATRUDNIONY>85/03/ 01</ZATRUDNIONY>
		<PLACA_POD>590</PLACA_POD>
		<ID_ZESP>20</ID_ZESP>
	</ROW>
	<ROW>
		<ID_PRAC>170</ID_PRAC>
		<NAZWISKO>JEZIERSKI</NAZWISKO>
		<ETAT>ASYSTENT</ETAT>
		<ID_SZEFA>130</ID_SZEFA>
		<ZATRUDNIONY>92/10/01</ZATRUDNIONY>
		<PLACA_POD>439,7</PLACA_POD>
		<PLACA_DOD>80,5</PLACA_DOD>
		<ID_ZESP>20</ID_ZESP>
	</ROW>
	<ROW>
		<ID_PRAC>190</ID_PRAC>
		<NAZWISKO>MATYSIAK</NAZWISKO>
		<ETAT>ASY STENT</ETAT>
		<ID_SZEFA>140</ID_SZEFA>
		<ZATRUDNIONY>93/09/01</ZATRUDNIONY>
		<PLACA_POD>371</PLACA_POD>
		<ID_ZESP>20</ID_ZESP>
	</ROW>
	<ROW>
		<ID_PRAC>180 </ID_PRAC>
		<NAZWISKO>MAREK</NAZWISKO>
		<ETAT>SEKRETARKA</ETAT>
		<ID_SZEFA>10 0</ID_SZEFA>
		<ZATRUDNIONY>85/02/20</ZATRUDNIONY>
		<PLACA_POD>410,2</PLACA_POD>
		<ID_ZESP>10</ID_ZESP>
	</ROW>
	<ROW>
		<ID_PRAC>200</ID_PRAC>
		<NAZWISKO>ZA KRZEWICZ</NAZWISKO>
		<ETAT>STAZYSTA</ETAT>
		<ID_SZEFA>140</ID_SZEFA>
		<ZATRUDNIONY>94/07/15</ZATRUDNIONY>
		<PLACA_POD>208</PLACA_POD>
		<ID_ZESP>30</ID_ZESP>
	</ROW>
	<ROW>
		<ID_PRAC>210</ID_PRAC>
		<NAZWISKO>BIALY</NAZWISKO>
		<ETAT>S TAZYSTA</ETAT>
		<ID_SZEFA>130</ID_SZEFA>
		<ZATRUDNIONY>93/10/15</ZATRUDNIONY>
		<PLACA_POD>250</PLACA_POD>
		<PLACA_DOD>170,6</PLACA_DOD>
		<ID_ZESP>30</ID_ZESP>
	</ROW>
	<ROW>
		<ID_PRAC>220</ID_PRAC>
		<NAZWISKO>KONOPKA</NAZWISKO>
		<ETAT>ASYSTENT</ETAT>
		<ID_SZEFA>110</ID_SZEFA>
		<ZATRUDNIONY>93/10/01</ZATRUDNIONY>
		<PLACA_POD>480</PLACA_POD>
		<ID_ZESP>20</ID_ZESP>
	</ROW>
	<ROW>
		<ID_PRAC>230</ID_PRAC>
		<NAZWISKO>HAPKE</NAZWISKO>
		<ETAT>ASYSTENT</ETAT>
		<ID_SZEFA>120</ID_SZEFA>
		<ZATRUDNIONY>92/09/01</ZATRUDNIONY>
		<PLACA_POD>480</PLACA_POD>
		<PLACA_DOD>90</PLACA_DOD>
		<ID_ZESP>30</ID_ZESP>
	</ROW>
</PRACOWNICY>
