=== EndymionSpr/SEWD_4/XML-Schema.zip_expanded/XML-Schema/IntegracjaSchematow/zesp.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  elementFormDefault="qualified" attributeFormDefault="unqualified"
  targetNamespace="www.pp.pl/zesp" xmlns="www.pp.pl/zesp">
  <xs:element name="ZESPOLY">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ROW" maxOccurs="unbounded" type="TZespRow"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="TZespRow">
    <xs:sequence>
      <xs:element name="ID_ZESP" type="xs:string"/>
      <xs:element name="NAZWA" type="xs:string"/>
      <xs:element name="ADRES" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== EndymionSpr/SEWD_4/XML-Schema.zip_expanded/XML-Schema/IntegracjaSchematow/zesp.xml
<?xml version="1.0" encoding="UTF-8"?>
<ZESPOLY xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="www.pp.pl/zesp zesp.xsd" xmlns="www.pp.pl/zesp">
	<ROW>
		<ID_ZESP>10</ID_ZESP>
		<NAZWA>ADMINISTR ACJA</NAZWA>
		<ADRES>PIOTROWO 3A</ADRES>
	</ROW>
	<ROW>
		<ID_ZESP>20</ID_ZESP>
		<NAZWA>SYSTEMY ROZPROSZONE</NAZWA>
		<ADRES>PIOTROWO 3A</ADRES>
	</ROW>
	<ROW>
		<ID_ZESP>30</ID_ZESP>
		<NAZWA>SYSTEMY EKSPERCKIE</NAZWA>
		<ADRES>STRZELECK A 14</ADRES>
	</ROW>
	<ROW>
		<ID_ZESP>40</ID_ZESP>
		<NAZWA>ALGORYTMY</NAZWA>
		<ADRES>WLODKOWICA 16</ADRES>
	</ROW>
	<ROW>
		<ID_ZESP>50</ID_ZESP>
		<NAZWA>BA DANIA OPERACYJNE</NAZWA>
		<ADRES>MIELZYNSKIEGO 30</ADRES>
	</ROW>
</ZESPOLY>
